import Nav from "";
import { Inter } from "";
import { Suspense } from "react";
import "./globals.css";
import getAllPosts from "./lib/getAllPosts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                <Nav />
                {children}
            </body>
        </html>
    )
}

// children = <Home />

// about page => page.js + layout.js

export const metadataa = {
    title: "",
    description: "",
}

export default function About() {
    return (
    <div></div>
    )
}


// blog page
export const metadataaa = {
    title: "",
    description: "",
}

export default function Blogs() {

    const blogs =[
    {
        id: 1,
        title: "A",
        description: "Allahu Akber",
    },
    {
        id: 1,
        title: "A2",
        description: "Alhamdulillah",
    },
    ]

    return (
        <div className="mt-10 constainer mx-auto text-center">
            <div className="font-bold"></div>
            <ul>
                {blogs.map(blog => (
                    <li key={blog.id}><Link href={`/blogs/${blog.id}`}>{blog.title}</Link></li>
                ))}
            </ul>

        </div>
    )
}

// [id] => dynamic params
export default function BlogPage({params}) {
    const id = params;

    return (
        <div>

        </div>
    )
}

// lib => Api

export default async function getAllPosts() {
    const result = await fetch("", {
        next: {
            revalidate: 10,
        },
    });
    
    return result.json();
}

// post page
export default async function pages() {
    const posts = await getAllPosts();


    return (
        <div>
            <h1>All Posts</h1>
            <ul>
                {posts.map(post => (
                    <li key={post.id} className=""><Link>{post.title}</Link></li>
                ))}
            </ul>
        </div>
    )
}

// [id] post dynamic page
export async function generateMetadata({params}) {
    const { id } = params;
    const post = await getPost(id);

    return {
        title: post.title,
        description: post.body,
    }
}

export default async function page({params}) {
    const { id } = params;
    const postPromise = getPost(id);
    const commentsPromise = await getPostComments(id);

    // const [post, comments] = await Promise.all([postPromise, commentsPromise])
    const post = await postPromise;


    return (
        <div>
            <h2>{post.title}</h2>
            <p>{post.body}</p>

            <Suspense fallback = "Loading ...">
                <Comments promise={commentsPromise} />
            </Suspense>
        </div>
    )

}

class Clock extends React.Component {
    state = {
        date: new Date(),
    }



    render() {
        const { date } = this.state;
        const { locale } = this.props;

        return (<div>
            <h1>My CLock</h1>
            <h2>{date.toLocaleTimeString(locale)}</h2>
        </div>)
    }
}