import getAllPosts from "@/lib/getAllPosts";
import Link from "next/link";

export const metadata = {
  title: "Posts",
  description: "Generated by create next app",
};

export default async function pages() {
  const posts = await getAllPosts();

  return (
    <div className="mt-6 container text-center mx-auto">
      <div className="font-bold text-9xl">📨</div>
      <h1 className="mb-10 font-bold text-9xl">All Posts</h1>
      <ul>
        {posts.map((post) => (
          <li
            key={post.id}
            className="my-2 text-2xl font-bold text-blue-500 hover:text-blue-700"
          >
            <Link href={`/posts/${post.id}`}>{post.title}</Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
