export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="container mx-auto text-center font-bold text-9xl">
      <div className="font-bold text-9xl">🪪</div>
      <div className="font-bold text-9xl">About page</div>
    </div>
  );
}
