import Link from "next/link";

export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function Blogs() {
  const blogs = [
    {
      id: 1,
      title: "Blog 1",
      description: "Blog 1 description",
    },
    {
      id: 2,
      title: "Blog 2",
      description: "Blog 2 description",
    },
  ];
  return (
    <div className="mt-10 container mx-auto text-center">
      <div className="font-bold text-9xl">🎼</div>
      <h1 className="font-bold text-9xl">Blogs</h1>
      <hr />
      <ul>
        {blogs.map((blog) => (
          <li
            key={blog.id}
            className="my-5 font-bold text-blue-500 hover:text-blue-700"
          >
            <Link href={`/blogs/${blog.id}`}>{blog.title}</Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
